### ISSUE TITLE
Model Thinning

### ISSUE THREAD

**Issue by macskay** [mkli90/pss#5]
- [x] Load SVG
- [x] detect symbol groups
- [x] ~~add PyQt Widget to show a given symbol group as image~~
- [x] added matplotlib figure to show to subplots, showing the original image and a skeletonized version
- [x] Add log-info, which tells what names are associated with the image shown (e.g. via index)
- [x] thin group models to one pixel width

Additional work:
- [x] #6 - Rename project
- [x] #7 - test_query.svg added, which is used to test the SvgHandler
- [x] #8 - Add .landscape.yaml to exclude "external"-folder from landscape scans

**Comment by mkli90** [comment]
- Also renamed project to "pss" for "Part-Structured Spotting"

**Comment by macskay** [comment]
GUI added in 6cf1fd8fc9a23807006725d7f225b2b1ec4e6f48

**Comment by macskay** [comment]
Added skeletonizing of symbol groups in 28660812b5580556c4f036de8c6b02bec6e538c8
